#ifndef FORDLOGO_H
#define FORDLOGO_H

#include "liblvgl/lvgl.h"

// Image data for imagePlease
// This is an example. You will need to replace this data with the actual image data generated by the LVGL image converter.
LV_IMG_DECLARE(fordLogo);

// Declare the image descriptor
extern const lv_img_dsc_t fordLogo;

#endif // IMAGEPLEASE_H
